name: "Check merge conflicts"
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  auto-label:
    runs-on: self-hosted
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          conflict_label_name: "merge-conflicts"
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # --- Optional Inputs ---
          # To make sure the merge commit exactly matches the branch
          detect_merge_changes: false # or true to handle as conflicts
          # By default a comment will be left, adding `conflict_comment: ''` will disable comments
          # The optional `${author}` will be replaced with the username of the pull request
          conflict_comment: |
            :wave: Hi, @${author},
            I detected conflicts against the base branch :speak_no_evil:
            You need to rebase :arrows_counterclockwise: your branch on the base!
